### ISSUE TITLE
Questions about businessKey field

### ISSUE THREAD

**Issue by c0ldd** [apache/incubator-kie-kogito-runtimes#1135]
Hi ! There is not a lot of information about this field. According [release notes](https://developers.redhat.com/blog/2020/03/20/kogito-0-8-0-features-online-editors-and-cloud-native-business-automation/) it should be "meaningful process IDs" and i can get process instance by this id. But when i call 

```curl -X POST "http://localhost:8080/blankprocess?businessKey=Key-111" -H  "accept: */*" -H  "Content-Type: application/json" -d "{}"```
then
``` curl -X GET "http://localhost:8080/blankprocess/Key-111" -H  "accept: application/json"```

I receive 404 
But if i call service with generated id 

```curl -X GET "http://localhost:8080/blankprocess/30800430-cc97-4793-a6d2-62a69424a7ee" -H  "accept: application/json"```

it's OK.
Tested on 1.0.0.FInal and 1.2.0.Final
Am i missing something ?

**Comment by vladimirfx** [comment]
Hit by this too in the context of forced sync process execution. Any thoughts from maintainers?

**Comment by fjtirado** [comment]
Hi, the usage of businessKey as described in the Release notes was deprecated with this JIRA https://issues.redhat.com/browse/KOGITO-2893
@hmanwani-rh can you check if current Release notes needs an update?

**Comment by hmanwani-rh** [comment]
> the usage of businessKey as described in the Release notes was deprecated with this JIRA https://issues.redhat.com/browse/KOGITO-2893
> @hmanwani-rh can you check if current Release notes needs an update?

@fjtirado Thanks for letting me know. However, I checked the latest Kogito 1.8 release notes and there is no mention of businessKey in that. Therefore, I do not think we need any update in the release notes. Please let me know if you've any questions.

**Comment by vladimirfx** [comment]
So, as a result of KOGITO-2893 we have:
- no way to provide own process id
- no way to access process instances by businessKey by any existing API (even listing of all process instances is not returned businessKey.)

Looks to me like hard functional degradation. Stateless systems (which can't store generated process ID) have no way to start the process with their own id and check the status later.

**Comment by vladimirfx** [comment]
> > the usage of businessKey as described in the Release notes was deprecated with this JIRA https://issues.redhat.com/browse/KOGITO-2893
> > @hmanwani-rh can you check if current Release notes needs an update?
> 
> @fjtirado Thanks for letting me know. However, I checked the latest Kogito 1.8 release notes and there is no mention of businessKey in that. Therefore, I do not think we need any update in the release notes. Please let me know if you've any questions.

There are no release notes where existing functionality is broken (search by businessKey). It is silently disabled without any notes and/or replacement - exactly what about this issue is.

**Comment by fjtirado** [comment]
@vladimirfx 
Yes, as you can see by looking at the JIRA description, there was no agreement on the team ( I was not here yet ;)) about the solution of this JIRA.

**Comment by vladimirfx** [comment]
> @vladimirfx
> Yes, as you can see by looking at the JIRA description, there was no agreement on the team ( I was not here yet ;)) about the solution of this JIRA.

Maybe provide at least a discrete API call to access process state by businessKey?

**Comment by fjtirado** [comment]
@vladimirfx  take a view to [data index ](https://github.com/kiegroup/kogito-runtimes/wiki/Data-Index-Service)

**Comment by vladimirfx** [comment]
@fjtirado Thanks, I know about the Data Index subsystem. But IMO it is on a different level of abstraction and it is optional. This issue is about low-level process management.
Can we obtain process instance ID by known businessKey without data index? If yes - I want to implement such API method.

**Comment by fjtirado** [comment]
@vladimirfx 
You are right, it is a different level of abstraction, but I think is still useful in the use case you mention. You store your business key somewhere else and use it to retrieve a "persistent" process that has been started a time ago, most likely already completed (note that Runtimes API only return process instances that have being finished if persistence addon is enabled) 
Runtime API only support process instance retrieval by using the generated process id. As indicated in Kogito-2893, the relation between generated process id and provided business key does not longer exist. So the answer is no, currently you can not retrieve process instance information by using runtime API using provided business key.

**Comment by vladimirfx** [comment]
Because of https://github.com/kiegroup/kogito-runtimes/issues/1214, we are stuck in our adoption of Kogito:
- no external process ID and way to discover generated process ID by external ID
- no way to start the process robustly (independent of process design) to retrieve generated process ID AND associate it with our own (external) ID

It is a very practical problem because we are trying to build a cloud-native decision engine using the Kogito stack. It takes 8 months of development and now I do not understand what to do with limitations. At the start of this project, we expect functional parity with jBPM but it seems I've been wrong...

Can you suggest a way to go?

**Comment by fjtirado** [comment]
The work around is to use curl -X POST "http://localhost:8080/blankprocess?businessKey=Key-111" -H "accept: */*" -H "Content-Type: application/json" -d "{}", which is still doable and then use Data Index (which although optional, it is intended to be used by any Kogito deployment) to retrieve process instance information associated to that businessKey.

**Comment by fjtirado** [comment]
I will also discuss with my colleagues if we should add/recover GET API to retrieve process instance id using businesskey as identifier (rather than the generate process id), but please took into account that if persistence is not enabled that will only return active (still in execution) instances, but it wont return process instances that has been completed. 
For such discussion, it will help if you can provide feedback about why data index is not usable in your context.

**Comment by elguardian** [comment]
outdated.
