### ISSUE TITLE
How to start process asynchronously?

### ISSUE THREAD

**Issue by vladimirfx** [apache/incubator-kie-kogito-runtimes#1214]
If the process is composed of service and script nodes only (no message node or human task) it runs to the end synchronously.

Current behavior:

1. Caller sends process start request (HTTP POST)
2. Kogito runtime starts the process instance
3. Kogito runtime runs the process instance to its end
4. **Kogito runtime return response to the caller (process instance id)**

If any node in the process executing a long time - the caller is failed by request timeout (but the process continues). So **caller has no chance to know the result of process execution** because:
- it has no process instance ID
- busnessKey is not working also #1135

Desired behavior:
1. Caller sends process start request (HTTP POST)
2. Kogito runtime starts the process instance
3. **Kogito runtime return response to the caller (process instance id)**
4. Kogito runtime runs the process instance to its end

IMO It is a very core concept of BPM to runs asynchronously. In the end, BPM is the state machine witch means it runs to some sort of "stops" and then continues. So it is not just (synchronous) script no matter what types of nodes it composes.

**Comment by vladimirfx** [comment]
Maybe duplicate of #1155

**Comment by ricardozanini** [comment]
Hi @vladimirfx! Sorry for the long delay.
For jBPM7, which Kogito is based on, we support marking any node as async. For Kogito, we don't have this feature just **yet**. There are other things to consider for this feature, and I'll let you know once we have it. If I may ask, could you share your context? This way, we can include it in our implementation plans.

**Comment by vladimirfx** [comment]
I need a robust way to start processes that not depends on process design (which nodes are used sync/async). BPM by its nature is a state machine which means it stops somewhere and waits for some event. So start the process and obtaining the result should be separate tasks. But now caller (starter) depends heavily on process design. It can't obtain process instance ID and check process later.
In most of our processes sync nodes stay in the beginning of the process and the process starter required to wait for these nodes to complete. Things becoming worst If an error occurred in the sync node and retry is configured - process start time is not practically acceptable. Because of https://github.com/kiegroup/kogito-runtimes/issues/1135 caller have no chance to check the process state later (by businessKey).
Actually, this issue and https://github.com/kiegroup/kogito-runtimes/issues/1135 is a showstopper in our adoption of Kogito.
It is a very annoying 'surprise' for BPM solution - no way to start the process without waiting for its sync nodes to complete + no way to find such started process later by own ID. So how to use it?

@ricardozanini I don't think there is any to do with jBPM 7. The solution is much simpler:
- validate start request
- allocate process instance (ID)
- start process run in the separate thread pool
- return process instance ID to the caller

It is what most BPMs actually do (even old-school jBPM which I've used in 200*). It can be implemented as request parameter or in its own start method. I can try to implement this solution and provide the PR. It is interesting to you?

**Comment by elguardian** [comment]
we don't support for now this. but you can achieve something similar with customAsync = true metadata in a node.

**Comment by DotNetPart** [comment]
> we don't support for now this. but you can achieve something similar with customAsync = true metadata in a node.

This actually leads to memory leaks...
We have a simple workflow with WorkItemHandler and Script Task. When we complete WorkItem in handler - it actually runs script task synchronously and doesn't return execution control until script task gets completed. That's not how we've expected this to be. 

Adding customAsync=true to Script Task node works better, but leads to memory leaks unfortunately...

**Comment by elguardian** [comment]
@DotNetPart Do you have more insight about this problem or something to share so we can test this ?
