### ISSUE TITLE
Return/handle of exception during process execution

### ISSUE THREAD

**Issue by rakeshnpatel** [apache/incubator-kie-kogito-runtimes#1248]
Currently, when the reusable subprocess node throws an exception during process execution, it is being captured by kogito and getting logged. The main process instance does not have the handle of the subprocess error and the state remains active. due to this when the REST resource (which starts the main process) skips the checkerror() since the state is active (1) and returns with HTTP response containing process variables instead of exception.

This also makes it impossible to use @controlleradvice to handle the exception and return meaningful response to clients who does not know whether process was success or failed.

This happens when you have re-usable sub process being called from parent process.

How do we stop the process and return the exception or get a handle of that exception to respond to client rather than responding with success.

**Comment by elguardian** [comment]
Retrieve exception from workflow execution is something we are not going to consider in the future as it would mean to leak engine problems to the end user.
