### ISSUE TITLE
Parent process remains in ACTIVE state when an exception occurs in re-usable subprocess 

### ISSUE THREAD

**Issue by rakeshnpatel** [apache/incubator-kie-kogito-runtimes#1258]
Scenario: you have a BPMN with re-usable subprocess being called from parent process.

if the sub process returns an exception (e.g. runtime exception), that sub process gets to state of ERROR (5) but the parent process remains in ACTIVE state (5) and the system responds with success response.

Also if you have listeners implemented (ProcessEventListener), you do not get a handle in any of the life cycle method for parent process since the process is not completed.

May be it would make sense to expose another lifecycle method, afterProcessErrored/Aborted so that application can get handle to decorate domain entities/perform some error handling.

Also parent process should not remain in ACTIVE state. it should get set with ERROR state with errors from subprocess being cascaded.

**Comment by elguardian** [comment]
outdated.
