### ISSUE TITLE
Provide a named listener annotation for Message Throws

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-kogito-runtimes#1926]
### Description

Very often a message is thrown but there is a associated implementation java class being called.  We should not assume that the use of Message Throws are going to be associated with the Events add on.  A message throw could be "send an email".

It looks like we ~could use a ProcessEventListener, but it would be a little more "clean" if we could do something like 

(not suggesting these should be the specific words used, I am only suggesting the spirit of the ability, and the finer naming details can be worked out during dev)

```java
...
    @Override
    @Event("MyMessageName", "OptionalProcessDefinitionId")
    public void event(EventThrow event) {
         // my impl details for what to do when the BPMN Event Throw occurs
    }
...
```

**Comment by fjtirado** [comment]
An for that, you should provide an email addon ;)
Thats the idea of Kogito, for any event publishing functionality, you should provide and addon that implements EventPublisher interface. 
And addon is just an additional maven depedency you include in your pom.xml that can be as simple as an implementation of EventPublisher that prints the event to the console
Thats the way Kogito is intender to be extended.

**Comment by StephenOTT** [comment]
@fjtirado does Kogito support multiple event publishers in parallel?

**Comment by fjtirado** [comment]
yes, Kogito loads all beans implementing EventPublisher interface and iterated through them
