### ISSUE TITLE
Process Instance Locking for Process Variables and other changes?

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-kogito-runtimes#1931]
### Description

The docs refer to locking being at the persistence level.  is the design to bubble these persistence locks to the process instance level?  

Example: Can two executions for the same Process Instance perform work in parallel?  If yes, how is this handled for parallel GET and UPDATE requests such as execution one is updating process variables, but execution two is doing a GET on the process variables.  

related to #1876 

Thanks

**Comment by fjtirado** [comment]
Beyond persistence, the concept of process instance lock does not exist. 
Therefore, if persistence is disable (which only make sense for a single node instalaltion of kogito), when you perform a get you obtain a copy of the data of the active process instance, and when you perform a PUT, the data of that process instance in memory is updated (that is a concurrent hash map, so it wont fail if there are two concurrent request). The GET performed at the same time will obtain either the data before the update or the data after the update. 
When persistence is enable, you will have the behaviour exposed by the underlying db. If optimistic locking is enable and there are two simultaneous PUT request, one of the two will fail and the user might rety.

**Comment by StephenOTT** [comment]
Thanks @fjtirado this is a common issue/design consideration in other BPM engines: given this i would ask that deep level of design considerations be documented for the provided persistence add ons as well as what should be considered for new persistence engines.  The lifecycle of when data is pulled from and pushed to persistence and considerations for parallel activity are going to topics people are looking to understand.
