### ISSUE TITLE
Multiple return values from a service task do not update process variables

### ISSUE THREAD

**Issue by tokarenko** [apache/incubator-kie-kogito-runtimes#2413]
### Describe the bug

I set up service task to return two variables as follows:
- Mapped service task outputs to process variables in "Data Outputs and Assignments" of BPMN editor;
- Implemented service task handler to return java Map<String, Object>:
```
@ApplicationScoped
public class Handler {
  public Map<String, Object> Execute() {
    Map<String, Object> results = new HashMap<>();
    results.put("processVariableA", true);
    results.put("processVariableB", "message");
    return results;
  }
}
```

Solution compiles and runs but process variables do not update with results and process does not transition further the service task and remains in "active" state:
```
Starting workflow 'Provisioning' (8ce17dc5-9606-425b-b563-a9deacdcc812)
Triggered node 'Start' for process 'Provisioning' (8ce17dc5-9606-425b-b563-a9deacdcc812)
Triggered node 'Set Variables' for process 'Provisioning' (8ce17dc5-9606-425b-b563-a9deacdcc812)
Workflow 'PortsProvisioning' (8ce17dc5-9606-425b-b563-a9deacdcc812) was started, now 'ACTIVE'
```

I checked Kogito source code and found that there are functions to set and get results as Map<String, Object>:
public void setResults(Map<String, Object> results)
public Map<String, Object> getResults()

### Expected behavior

Process variables update with results returned from service task as java Map<String, Object>

### Actual behavior

Process variables do not update with results returned from service task as java Map<String, Object> and process does not transition further the service task and remains in "active" state

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19

**Comment by tokarenko** [comment]
I suppose that the issue may be in [ServiceTaskHandler.java](https://github.com/kiegroup/kogito-runtimes/blob/49c622f08f3803d27d0585adfdeabe93200f642e/jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/handler/ServiceTaskHandler.java)

Current implementation puts result object into results HashMap with resultVarName irrespective of the fact that result may be itself a HashMap.

```
public class ServiceTaskHandler implements KogitoWorkItemHandler {
    ...
    private String resultVarName;
    ...
    public ServiceTaskHandler(String resultVarName) {
        this.resultVarName = resultVarName;
    }
    ...
    public void executeWorkItem(KogitoWorkItem workItem, KogitoWorkItemManager manager) {
    ...
    Object result = method.invoke(instance, params);
    Map<String, Object> results = new HashMap<>();
    results.put(resultVarName, result);
    manager.completeWorkItem(workItem.getStringId(), results);
```

**Comment by fjtirado** [comment]
@tokarenko The scenario you are describing should work. 
Im assuming you check https://github.com/kiegroup/kogito-examples/tree/stable/kogito-quarkus-examples/process-service-calls-quarkus
Im going to test a service returning a map object in my end, but since I think this depends on how the output assigment is set, it would be nice if you can share those (the assignments in your bpmn, Im assuming the java service is the one you describe)

**Comment by fjtirado** [comment]
Opened JIRA https://issues.redhat.com/browse/KOGITO-7844 to implement that

**Comment by krisv** [comment]
ServiceTask was designed to only return one result, as this matches with invoking a Java operation, which also just returns one Object.  Automatically turning a HashMap into multiple results would be possible (and quite trivial), but it would be difficult for the engine to guess if that's what the process designer wants or not (as the other case where a hashmap is considered as one result might be valid too).  A service task is nothing more than an implementation of a custom work item node, how about just having your own custom work item that does what you expect?
