### ISSUE TITLE
Support for Correct Long/Double/Float in RunTime with MongoDB Persistence

### ISSUE THREAD

**Issue by debu999** [apache/incubator-kie-kogito-runtimes#2709]
### Description

When we use long/double/float the persistence changes in mongodb
Refer to the data persisted in the variable
double / float gets rounded of during mongodb persistence and precision is lost.

![Screenshot 2022-12-23 at 10 12 00 AM](https://user-images.githubusercontent.com/1910577/209272279-712ff10f-8800-4880-8c51-9d326b578a3b.png)

"variable": [
      {
        "name": "dbl",
        "dataType": "java.lang.Double",
        "value": {
          "@type": "type.googleapis.com/google.protobuf.DoubleValue",
          "value": 2.1348234663853e+34
        }
      },
      {
        "name": "flt",
        "dataType": "java.lang.Float",
        "value": {
          "@type": "type.googleapis.com/google.protobuf.FloatValue",
          "value": 1.2028235e+34
        }
      },
      {
        "name": "i",
        "dataType": "java.lang.Integer",
        "value": {
          "@type": "type.googleapis.com/google.protobuf.Int32Value",
          "value": 2147483641
        }
      },
      {
        "name": "lng",
        "dataType": "java.lang.Long",
        "value": {
          "@type": "type.googleapis.com/google.protobuf.Int64Value",
          "value": "8223372036854775802"
        }
      }
    ]
 

### Implementation ideas

add parser for the below datatypes
Payload
{
  "lng": 8223372036854775802,
  "i": 2147483641,
  "dbl": 21348234663852886984636272864657746.234566,
  "flt": 12028234663852423984636272836465776.837366
}
Response
{
  "id": "cb8271db-e290-4c6f-b2d9-ceb0d8a0cd13",
  "lng": 8223372036854776000,
  "i": 2147483641,
  "dbl": 2.134823466385289e+34,
  "flt": 1.2028235e+34
}

Seems the data in db is correct for long but response rounds it off for some reason.

**Comment by debu999** [comment]
@nmirasch is this now being developed.

**Comment by debu999** [comment]
any update on this.

**Comment by nmirasch** [comment]
Hello @debu999, We are adding support for Long/Float/Double with their specific GraphQL type in https://github.com/kiegroup/kogito-apps/pull/1593 and that improves the precision and avoids the rounding problem you detected, when getting the stored values from database.
