### ISSUE TITLE
Serverless Workflow: Support for publishing events in Kafka using Cloud Events in binary mode.

### ISSUE THREAD

**Issue by gpando** [apache/incubator-kie-kogito-runtimes#3115]
### Description

Support for publishing events in Kafka using Cloud Events in binary mode. 
Currently, it only allows structured mode.

**Comment by fjtirado** [comment]
Support for sending events on binay mode was added with https://github.com/apache/incubator-kie-kogito-runtimes/pull/3386. Setup instruction are there and will be incorporated to documentation
