### ISSUE TITLE
Support for `resultEventRef` in Actions for Kogito Serverless

### ISSUE THREAD

**Issue by dfiai** [apache/incubator-kie-kogito-runtimes#3245]
### Description

Hello everyone, I want to express my appreciation for your outstanding work! I'm curious if there are any plans to introduce support for resultEventRef in actions, as outlined in specification version 0.8x? While I understand that it can currently be emulated within callback states, its absence in parallel and foreach states is of utmost importance for my use case.

**Comment by fjtirado** [comment]
There are not currently plans to support them in 0.8 implementation. Please note that you can include subflows in a parallel branch and that subflows can use intermediate (not starting ones) event states to stop that branch (Im assuming the first that a parallel branch will do is not consume the event, for that purpose, see next parragraph). You can do the same in for each, but I do not recomment to stop the loop waiting for an event, it wont have much sense.   
Also note that if your goal is to consume several event types and depending on the event type you want to execute one action or another you can associate a set of event types with a set of actions using event type.

**Comment by dfiai** [comment]
@fjtirado, thanks for your comment! I believe subflows should work for me.
