### ISSUE TITLE
Bump openapi generator version to a version that includes https://github.com/quarkiverse/quarkus-openapi-generator/pull/556

### ISSUE THREAD

**Issue by gabriel-farache** [apache/incubator-kie-kogito-runtimes#3284]
### Description

https://github.com/quarkiverse/quarkus-openapi-generator/pull/556 fixed an error that should be integrated to the runtime.

So the openapi generator version should be bumped to the new release that includes the fix.

### Implementation ideas

Update `version.io.quarkiverse.openapi.generator` in `kogito-build/kogito-dependencies-bom/pom.xml`

**Comment by ricardozanini** [comment]
Released: https://github.com/quarkiverse/quarkus-openapi-generator/pull/566

@gabriel-farache feel free to open a PR to update to the new version.
