### ISSUE TITLE
Event catching error for intermediate event in spring boot

### ISSUE THREAD

**Issue by sandeepchaudhary1093** [apache/incubator-kie-kogito-runtimes#3363]
### Describe the bug

Ref: https://blog.kie.org/2021/09/kogito-process-eventing-add-ons.html#comment-357

Regarding : kogito-process-eventing-add-ons
Issue on build tool : spring boot
issue: There is an issue in SpringBoot receiver class, which only listen for topics on default channel and ignore any other one.

For catching intermediate event in workflow with spring boot, i had provided below properties

kogito.addon.cloudevents.kafka.kogito_incoming_stream=start
kogito.addon.cloudevents.kafka.kogito_incoming_stream.intermediate=intermediate
kogito.addon.cloudevents.kafka.kogito_outgoing_stream=end

now after starting the workflow with “start” topic message, when i send a message to “intermediate” topic with the process instance id and type=”intermediate”, the workflow doesn’t recognise it.

However if I send the same message to “start” topic with process inst id and type=”intermediate” then the message gets caught and the workflow continues.

So only incoming and outgoing properties are recognised not the node specific(intermediate).

### Expected behavior

For :
kogito.addon.cloudevents.kafka.kogito_incoming_stream=start
kogito.addon.cloudevents.kafka.kogito_incoming_stream.intermediate=intermediate

Event sent to "intermediate" topic with process instance id should be caught by workflow and workflow should progress.

### Actual behavior

Only while sending event to "start" topic with "type": "intermediate" and process inst id works.

Events sent to "intermediate" topic are not recognised by workflow.

### How to Reproduce?

1. add a bpmn2 file with start, end and intermediate message event.
2. send event to start message and then to intermediate event node.
3. event to intermediate gets ignored.

**Comment by fjtirado** [comment]
As described, multiple channels for springboot is not working as expected. We need to generate different receivers. Working on it

**Comment by sandeepchaudhary1093** [comment]
Thanks for fixing the issue , may i know when would it be available and in which version of kogito/dependency ?

**Comment by fjtirado** [comment]
Tomorrow, you can try updating snapshot, make sure that in your example you are using 999-SNAPSHOT as kogito version

**Comment by fjtirado** [comment]
All of them

**Comment by fjtirado** [comment]
Ok, probably this is related with the repository you are using, make sure that in your pom.xml you have 
<repositories>
    
    <repository>
        <id>apache-public-repository-group</id>
        <name>Apache Public Repository Group</name>
        <url>https://repository.apache.org/content/groups/public/</url>
        <layout>default</layout>
        <releases>
            <enabled>true</enabled>
            <updatePolicy>never</updatePolicy>
        </releases>
        <snapshots>
            <enabled>true</enabled>
            <updatePolicy>daily</updatePolicy>
        </snapshots>
    </repository>
  </repositories>

**Comment by sandeepchaudhary1093** [comment]
This worked, thanks a lot @fjtirado.

In which Kogito version can we expect this feature to be released in ?

**Comment by fjtirado** [comment]
@sandeepchaudhary1093 
I do not know which is the release schedule (and honestly I prefer to live in ignorance regarding that)
Please ask here https://kie.zulipchat.com/
