### ISSUE TITLE
kogito-quarkus support

### ISSUE THREAD

**Issue by Emiliopg91** [apache/incubator-kie-kogito-runtimes#3398]
### Description

Hi, 

In my organization, we use quarkus 3.X for our corporative framework and we need kogito for certain business proceses.
But we have the problem that latest version pubished in maven-central (2.44.0.Alpha) doesn't support quarkus 3 due to jakarta packages.

When will you release any version with full support for  quarkus 3 and jakarta packages? 

Thank you!

**Comment by Emiliopg91** [comment]
@ricardozanini 
Thank you so much!

Could you tell me when do you expect the CI to be fixed and the sofware to be released?

**Comment by indiealexh** [comment]
Following up on this. Is there any timeline for or release schedule for Kogito?

**Comment by porcelli** [comment]
it's expected that we'll branch this week!

**Comment by koskom-alt** [comment]
Hi!
We are also really looking forward to the stable version. How soon is it?)

**Comment by cl3rk90** [comment]
Hello there,
any news on this matter?

Thank you very much for your work!

**Comment by ricardozanini** [comment]
We are still working on the release, we are getting there! 😅

**Comment by fedemori** [comment]
Hi, do you have an ETA for the release ok Kogito with Quarkus 3?

**Comment by indiealexh** [comment]
> it's expected that we'll branch this week!

I think I must have misunderstood what this meant xD Any news?

**Comment by porcelli** [comment]
https://lists.apache.org/thread/g164c2z9y82l3bprmpn132zdwjk2nds8

**Comment by cvgaviao** [comment]
Hello. Is there news on this subject?

**Comment by louisaoc** [comment]
Hi there. any news on the Quarkus 3 compatibility?

**Comment by porcelli** [comment]
we are likely to run RC3 this week, so expected to have something out soon.

**Comment by indiealexh** [comment]
I saw the release vote closed on Thursday and there is a couple action items but looks like we are close?

**Comment by porcelli** [comment]
blockers were found by IPMC, we are working to have rc4 this week

**Comment by knuspertante** [comment]
Hey @porcelli do you have any news for us on this topic?

**Comment by porcelli** [comment]
10.0.0 has been released! https://kie.apache.org/blog/kie_10_0_0_release
