### ISSUE TITLE
Add node duration metric to monitoring addon

### ISSUE THREAD

**Issue by fjtirado** [apache/incubator-kie-kogito-runtimes#3483]
### Description

It would be interesting to track the duration of certain nodes, as we are tracking process instances duration and all work items duration

### Implementation ideas

In BPMN and SWF parsers, add a metadata key called "Metric" to those nodes that it will be interesting to track duration for.
In monitoring addon, add a new Distributionsummary object called ""kogito_node_instance_duration_seconds" which will record duration for those nodes flagged with the metadata key.

**Comment by fjtirado** [comment]
@elguardian Should I change the BPMN parser to add the metric metadata to certain nodes (in that case we need to dicuss which ones)  or do you prefer to do that with a follow up issue?

**Comment by elguardian** [comment]
there is no need to change the parsec... the editor has already a metadata section. so you just need to take that into account in the runtime

**Comment by fjtirado** [comment]
> there is no need to change the parsec... the editor has already a metadata section. so you just need to take that into account in the runtime

Sure, I mean, add to the parser logic a call to metadata ("metric", "<node name in metric tag>") for those nodes which duration should be recorded
