### ISSUE TITLE
onErrors not invoked from event state

### ISSUE THREAD

**Issue by deepakkapoor23** [apache/incubator-kie-kogito-runtimes#3571]
### Describe the bug

If an action within event state encounters error, onErrors block is not invoked.
This appears to work fine for an operation state.

[serverless-workflow-error-quarkus.zip](https://github.com/user-attachments/files/16087926/serverless-workflow-error-quarkus.zip)

### Expected behavior

onErrors should be invoked regardless of state type

### Actual behavior

onErrors is not onvoked for an event state, instead the event is rejected with an exception

### How to Reproduce?

Please see readme on attached project to reproduce the issue.

### Output of `uname -a` or `ver`

Windows 11

### Output of `java -version`

17

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.6

**Comment by deepakkapoor23** [comment]
For some reason, its unable to generate source with error handler in eventjoke workflow and fails the build. This is new didnt happen on my project earlier. The VS code plugin seems to generate the svg fine with right connections so I am not sure why the code gen doesnt like it...

**Comment by fjtirado** [comment]
This is hapenning when the event state is a start one. Needs to be fixed
