### ISSUE TITLE
Allow user to get current datetime in workflow

### ISSUE THREAD

**Issue by gabriel-farache** [apache/incubator-kie-kogito-runtimes#3602]
### Description

I njq we can run `jq -n now` to get the current datetime, it would be nice to be able to do that in the workflow

**Comment by fjtirado** [comment]
We will add $WORKFLOW.currentmillis, which will provide the number of milliseconds from 1970  and $WORKFLOW.datetime, which will return an ISO 8601 string with the timezone offset

**Comment by mcruzdev** [comment]
Could I help with this one @fjtirado?

**Comment by fjtirado** [comment]
We will be adding $WORKFLOW.now.iso8601, $WORKFLOW.now.epochMillis and $WORKFLOW.now.epochNanos

**Comment by fjtirado** [comment]
I realize jq has  a now built-in function
`now` is working, but` now | strftime("%Y-%m-%dT%H:%M:%SZ")` is not. Lets fix that.

**Comment by fjtirado** [comment]
@gabriel-farache Once the attached PR is in
You can write  ` timestamp | strftime(\"yyyy-MM-dd'T'HH:mm:ss.SSSZ\")`
To get  current date time in ISO format
