### ISSUE TITLE
Workflow finalizer / abort hook

### ISSUE THREAD

**Issue by gabriel-farache** [apache/incubator-kie-kogito-runtimes#3674]
### Description

The way we currently to it is by updating the state via a graphQL mutation request sent to the DI so there is no known way to me to execute a state that is executed before aborting the workflow.

This would be nice to be able to set a finalizer / abort hook that is always executed when canceling the workflow: if the workflow already started some external execution or made some changes, it would be nice to be able to revert those.

**Comment by gabriel-farache** [comment]
If the DELETE call that abort a workflow would throw an exception, then by configuring a global, or by state, `onErrors` catching the thrown exception would solve the issue:
```
onErrors:
      - errorRef: abort
        transition: compensate
```

**Comment by fjtirado** [comment]
After discussing this issue further, I think we can automatically execute compesating states if the workflow is aborted by calling delete endpoint.
