### ISSUE TITLE
Error when building workflow with openapi spec with multipart content

### ISSUE THREAD

**Issue by gabriel-farache** [apache/incubator-kie-kogito-runtimes#3723]
### Describe the bug

With 1.34.0 when building I have the following error:

> [ERROR] /home/kogito/serverless-workflow-project/target/generated-sources/open-api-stream/org/kie/kogito/openapi/movekube/api/WorkspaceInputsApi.java:[61,60] package org.jboss.resteasy.annotations.providers.multipart does not exist

See enclosed the openapi spec file
[move2kube.zip](https://github.com/user-attachments/files/17364723/move2kube.zip)

### Expected behavior

No issue when building the workflow

### Actual behavior

Error

### How to Reproduce?

1. Create a workflow
2. Use the enclosed spec or any spec with multipart and/or application/x-www-form-urlencoded content
3. Build the workflow using OSl 1.34 (registry.redhat.io/openshift-serverless-1/logic-swf-builder-rhel8@sha256:9a4093e195bec163c609381e3c0ceeec55f6e229c6a1def6f362517886faea71)
4. See the error

**Comment by fjtirado** [comment]
This is a dependency issue which is fixed by manually adding io.quarkus:quarkus-resteasy-multipart dependency. 
We need to discuss if we should add this automatically in the quarkus extension or not.

**Comment by gabriel-farache** [comment]
I'm good with that too as long as it is well documented.
Is there, somewhere in your website/doc, a list of all available extensions that can/could/should be used with a description?

**Comment by fjtirado** [comment]
@gabriel-farache We are checking if the dependency is small enough to be automatically added in the quarkiverse extention.

**Comment by ricardozanini** [comment]
@fjtirado @gabriel-farache this is already in the doc: https://docs.quarkiverse.io/quarkus-openapi-generator/dev/client.html#sending-multipart-formdata

So I assume we are still on RESTeasy Classic, @fjtirado?

**Comment by gabriel-farache** [comment]
@ricardozanini It's not in your doc, it's in the openapi generator doc, which is the tool you are using.
I mean, the dependency was removed in the sontaflow builder project hence causing issue to end-user.

As an end-user I may not be aware of all the technicalities and tools you are using behind the hood that's why I was suggesting to have a page in your doc stating which dependencies could be added, and even give advices, like: "you want to use multipart content-type in your api spec, make sure to include this dependency and check other available at https://..." 
Because if an end-user, not familiar with quarkus or how everything is built has en error about multipart not supported, if there is no place in your doc (so the product they are using) helping them to sort things out, it may be time consuming for them :)

**Comment by ricardozanini** [comment]
It was. just a reminder to Javi. We will surely add it to our docs or directly on our side.
