### ISSUE TITLE
Dates are visualized as numbers in the UI

### ISSUE THREAD

**Issue by fjtirado** [apache/incubator-kie-kogito-runtimes#3778]
### Description

In general, for display representation purposes and also for jq filtering, Dates should be handled as string. 
For example, if an openapi server returns a date, the representation of the workflow model that is written into the UI is 
```
{
  "id": "1",
  "dateTime": 1731585490.4387977,
  "correlation": "w1",
  "description": "call"
}
```

### Implementation ideas

Add disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS) to ObjectMapper.

**Comment by tiagobento** [comment]
Shouldn't this be handled in the UI instead? Or maybe have both formats in the API?
